---
driver:
  name: vagrant
  network:
  - ['private_network', {type: 'dhcp'}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[opengrok::default]
    attributes:
  - name: non_default_properties
    run_list:
      - recipe[opengrok_test::non_default_properties]

