---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
  - name: opensuse-13.2
  - name: opensuse-leap-42.1

suites:
  - name: helloworld
    run_list:
      - recipe[opengrok_test::helloworld]
  - name: non_default_properties
    run_list:
      - recipe[opengrok_test::non_default_properties]

