driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

platforms:
- name: centos-7
  driver:
    image: centos:7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
    intermediate_instructions:
      - RUN yum -y install lsof which systemd-sysv initscripts

- name: opensuse-13.2
  driver:
    image: opensuse:13.2
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive which net-tools

- name: opensuse-42.1
  driver:
    image: opensuse:42.1
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN zypper --non-interactive install aaa_base perl-Getopt-Long-Descriptive which net-tools

- name: ubuntu-16.04
  driver:
    image: ubuntu:16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install net-tools

suites:
  - name: helloworld
    run_list:
      - recipe[opengrok_test::helloworld]
  - name: non_default_properties
    run_list:
      - recipe[opengrok_test::non_default_properties]

