name 'cookbook-opengrok'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cookbook-opengrok'
long_description 'Installs/Configures cookbook-opengrok'
version '0.1.0'
